// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvpokzjpbltqxmtvqdhc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12cG9rempwYmx0cXhtdHZxZGhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NTM2OTksImV4cCI6MjA3MDUyOTY5OX0._5dtBCWwQGHkKt5HFAQLcrEJETxh2dQS4dhYaDqT418";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});